name: Deploy Pizza to Debian

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: |
            ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy to Debian Server
        run: |
          ssh -v -i ~/.ssh/id_ed25519_web2 ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }} "echo SSH OK"
          set -e
          ssh -o StrictHostKeyChecking=no ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }} << 'EOF'
          set -e
          cd /var/www/web2
          echo "BEFORE: $(git rev-parse --short HEAD)"
          git fetch origin main
          git reset --hard origin/main
          echo "AFTER:  $(git rev-parse --short HEAD)"
          sudo systemctl reload nginx
          EOF